### ISSUE TITLE
how to build and publish @test/ui and @test/utils 

### ISSUE THREAD

**Issue by baurine** [Innei/pnpm-workspace-monorepo#2]
hi @Innei , in this pnpm monorepo template, how do we build and publish the `@test/ui` and `@test/utils` packages, so other projects can install and use them?

**Comment by Innei** [comment]
hi @baurine, I update template just now, and add how to build monorepo script. When in pnpm monorepo pack, monorepo package will automatically change the version number, replace `workspace:*` to semver. So publish the mono package just like publish a normal package. cd to the package path, and do `pnpm publish`, or you can write a script in root script, `pnpm publish -r`, it will do publish recursive.

**Comment by Innei** [comment]
E.g. `@test/utils`,

```sh
cd packages/utils
pnpm run build
pnpm publish
```

or in root dir.

```sh
pnpm run build -C packages/utils
pnpm run publish -C packages/utils
```

**Comment by zjtt** [comment]
why not use --filter? What is the difference between -C and --filter?

**Comment by Innei** [comment]
> why not use --filter? What is the difference between -C and --filter?
> 
> 
> 
> 

-C package_path

--filter package_name

**Comment by baurine** [comment]
hi @Innei , I tried the latest code, found some new issues:

First, I can't start the `web` packages by `pnpm run dev -r` or `cd packages/web && pnpm run dev` likes before. It says:

```
$ pnpm run dev -r
Scope: all 4 workspace projects
packages/web dev$ vite
│ ✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "@test/ui". The package may have incorrect main/module/export
│     ../../node_modules/.pnpm/vite@2.8.2/node_modules/vite/dist/node/chunks/dep-3d5f2596.js:29521:10:
│       29521 │     throw new Error(`Failed to resolve entry for package "${id}...
...
```

I think this is expected because the `main` field is changed for @test/ui and @test/utils from "`index.ts|tsx` to `./dist/index.js` and they doesn't exist before building.

If I run `pnpm run build -r`, it will build @test/utils and @test/ui only, because we lack the build script for @test/web. After adding `"build": "vite build"` for @test/web, and run `pnpm run build -r`, all packages are built. But it fails when building @test/web, it says:

```
$ pnpm run build -r
Scope: all 4 workspace projects
. build$ pnpm run build -r
│ Scope: all 4 workspace projects
│ packages/utils build$ tsc
│ packages/utils build: Done
│ packages/ui build$ tsc
│ packages/ui build: Done
│ packages/web build$ vite build
│ packages/web build: vite v2.8.2 building for production...
│ packages/web build: transforming...
│ packages/web build: Error when using sourcemap for reporting an error: Can't resolve original location of error.
│ packages/web build: 'Hello' is not exported by ../ui/dist/index.js, imported by index.tsx
│ packages/web build: file: /mnt/bao/codes/personal/try-pnpm/pnpm-workspace-monorepo-old/packages/web/index.tsx:2:9
│ packages/web build: 1: import React from "react";
│ packages/web build: 2: import { Hello } from "@test/ui";
│ packages/web build:             ^
│ packages/web build: 3: import { add } from "@test/utils";
│ packages/web build: 4: import ReactDOM from "react-dom";
│ packages/web build: ✓ 25 modules transformed.
│ packages/web build: error during build:
│ packages/web build: Error: 'Hello' is not exported by ../ui/dist/index.js, imported by index.tsx
```

Although I don't know why, because it seems `Hello` is exported by @test/ui.

Then I run `pnpm run dev -r` to start the @test/web in dev mode, the browser console also report `Hello` is not exported.

![image](https://user-images.githubusercontent.com/1284531/154185238-88e8d612-c3e1-4b0d-bbaf-3223313e2bf5.png)

Can you make a full example to demonstrate:

1. how to use one command to start the project for dev mode, likes `pnpm run dev -r`, it should also watch all the packages changes and build them automatically.
2. how to use one command to build the project for production mode, likes `pnpm run build -r`.

Thanks!

**Comment by Innei** [comment]
Hi, It's my fault, library output type should be esm, but got cjs, vitejs can't resolve cjs exports there.

And, I updated web dev script just now, it worked.

**Comment by baurine** [comment]
Big thanks! Let me have a try.

> library output type should be esm, but got cjs, vitejs can't resolve cjs exports there.

From my former practice, vite would convert the cjs dependency to esm automatically for us. For example, we can use `import {min} from 'lodash'` directly. (lodash is cjs format while lodash-es is esm format, I remember). Or maybe it just convert the cjs from the node_modules, I would check it later.

**Comment by Innei** [comment]
Yes, it will convert cjs to esm, but I do not know why it can not convert here. Maybe there are some problem in tsconfig.json

**Comment by baurine** [comment]
I updated the code, remove `packages/web/node_modules` folder to remove the vite cache, then run `pnpm install && pnpm run dev:web`, it reports following errors:

```
[0]   The plugin "vite:dep-scan" was triggered by this import
[0] 
[0]     index.tsx:3:20:
[0]       3 │ import { add } from '@test/utils'
[0]         ╵                     ~~~~~~~~~~~~~
[0] 
[0] error when starting dev server:
[0] Error: Build failed with 2 errors:
```

But `pnpm run build` works fine, and the output `packages/web/dist` works as expected by running `serve .`

![image](https://user-images.githubusercontent.com/1284531/154192162-d800301a-9460-48d4-9f4c-1f15356da591.png)

After running `pnpm run build`, run `pnpm run dev:web` again, now it works fine, and can watch the @test/utils and @test/ui files changes, reload the page automatically, great!

![image](https://user-images.githubusercontent.com/1284531/154192611-5a956a30-f7eb-42cc-9507-e18fbe978a9e.png)

PS: please add `node_modules` to the `.gitignore` to avoid thousands of files changes in local.

**Comment by Innei** [comment]
I think should add prepare script `pnpm run build `in root package.

**Comment by Innei** [comment]
In my habit, add node_modules gitignore in `~/.gitignore`, so it will ignore globally.
